name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install md4c notcurses
      - name: Build
        run: make
      - name: Test (ASan/UBSan)
        run: make test
